### ISSUE TITLE
Typeerror in profileStore.py

### ISSUE THREAD

**Issue by iambillmccann** [Joe-McCann/LetsHang-BackEnd#2]
**Repro**
1. Start the backend and frontend
2. Log onto Let's Hang
3. Sign up for a new account (I used Facebook for authentication)
4. Fill in the profile form
5. Click the Get Started link
6. Click continue
7. Click the plus sign to add an invitee
8. Fill in the form and click Ok
9. Click continue to view the map
10. Click Save
11. Tab to the backend console window

**Actual Results**
The backend displays the following stack trace to the console window:

```
[2018-06-29 15:31:01 -0400] [24] [ERROR] Error handling request /friends/facebook%7C10212720021288622
Traceback (most recent call last):
  File "/mnt/e/Bill/Documents/GitHubProjects/LetsHang-BackEnd/testing/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/mnt/e/Bill/Documents/GitHubProjects/LetsHang-BackEnd/testing/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/mnt/e/Bill/Documents/GitHubProjects/LetsHang-BackEnd/testing/lib/python3.5/site-packages/falcon/api.py", line 247, in __call__
    if not self._handle_exception(ex, req, resp, params):
  File "/mnt/e/Bill/Documents/GitHubProjects/LetsHang-BackEnd/testing/lib/python3.5/site-packages/falcon/api.py", line 677, in _handle_exception
    err_handler(ex, req, resp, params)
  File "/mnt/e/Bill/Documents/GitHubProjects/letsHang-BackEnd/letshang/app.py", line 35, in generic_error_handler
    raise ex
  File "/mnt/e/Bill/Documents/GitHubProjects/LetsHang-BackEnd/testing/lib/python3.5/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/mnt/e/Bill/Documents/GitHubProjects/letsHang-BackEnd/letshang/resources/friends.py", line 34, in on_get
    profiles = profileStore.ids2Profiles(friends)
  File "/mnt/e/Bill/Documents/GitHubProjects/letsHang-BackEnd/letshang/firebase/profilestore.py", line 188, in ids2Profiles
    userId = friendIds['id']
TypeError: 'NoneType' object is not subscriptable
```

**Expected Results**
No exception should be raised.

**Comment by iambillmccann** [comment]
This issue occurs when the user first logs on after signing up for let's hang.

Strange. When I created a new user via Twitter, the backend did not throw an exception. When I log on with existing accounts, it does not throw an exception. Microsoft did not throw an exception. I am forced to delete all the accounts and start over.
